Create Footer
DanteBorges/Professional_portfolio pull request #3
Opened 2022-01-19 21:14 UTC by DanteBorges

2022-01-20 17:18 UTC, natandias requested changes
Please, remove the .eslintcache file and put it on the .gitignore file.
There's also a bug in the mobile visualization of the footer on smaller screens.
![Captura de tela de 2022-01-20 14-04-14](https://user-images.githubusercontent.com/49736127/150388353-98275b85-d932-4f11-ab2f-75b15a4f3fa7.png)

The contrast of the text on the footer is not good. The contrast ratio is under 4, which makes it quite unreadable. You could use white color for the text, which would improve the contrast ratio to above 6. You can also use this site: https://webaim.org/resources/contrastchecker/ to test colors contrast. 
![Captura de tela de 2022-01-20 14-01-59](https://user-images.githubusercontent.com/49736127/150388570-15d2cf07-0c42-4f27-a617-97d681202dee.png)

2022-01-20 17:18 UTC, natandias commented on src/components/Footer/index.js
> +            <a
Consider using rel="noopener" on your links to improve security: https://web.dev/external-anchors-use-rel-noopener/.

2022-01-20 17:18 UTC, natandias commented on src/components/Footer/index.js
> +const navigation = {
Maybe you could change this object to a separate file, to make this file a bit cleaner.

2022-01-21 21:45 UTC, emersonlopxs commented on .eslintcache
> +[{"D:\\Users\\Daniel\\Desktop\\Programação\\professional_portfolio\\src\\index.js":"1","D:\\Users\\Daniel\\Desktop\\Programação\\professional_portfolio\\src\\App.js":"2","D:\\Users\\Daniel\\Desktop\\
pode colocar esse arquivo `.gitignore`

2022-01-21 21:47 UTC, emersonlopxs commented on src/components/Footer/index.js
> +    { name: "Hire me", href: "#" },
These `href`s should point something, otherwise could be removed.

2022-01-21 21:47 UTC, emersonlopxs commented on src/components/Footer/index.js
> +        <svg fill="currentColor" viewBox="0 0 24 24" {...props}>
Can we move this image to a `.svg` file inside an images?

2022-01-21 21:48 UTC, emersonlopxs commented on src/components/Footer/index.js
> +        <svg
Same as above

2022-01-21 21:48 UTC, emersonlopxs commented on src/components/Footer/index.js
> +        <svg fill="currentColor" viewBox="0 0 24 24" {...props}>
Same as above

2022-01-26 18:39 UTC, merged