Hire me added
DanteBorges/Professional_portfolio pull request #5
Opened 2022-01-19 21:48 UTC by DanteBorges

2022-01-20 17:43 UTC, natandias requested changes
Take these as suggestions: I know you're not sending the data of the form yet, but it would be great if I had validation on the fields. Also, I don't know if this should be done in this PR, or if you're going to do it later, but the click on the 'Hire me' button doesn't redirect to the section.

2022-01-20 17:43 UTC, natandias commented on src/components/HireMe/index.js
> +*/
Can these comments be removed?

2022-01-20 17:43 UTC, natandias commented on src/components/HireMe/index.js
> +                <textarea
Block the resize of the textarea: https://pt.stackoverflow.com/questions/177917/como-desabilitar-o-resize-do-textarea.

2022-01-21 21:51 UTC, emersonlopxs commented on src/components/HireMe/index.js
> +        console.log(result.text);
Can we remove this `console.log`?

2022-01-21 21:51 UTC, emersonlopxs commented on src/components/HireMe/index.js
> +        console.log(error.text);
Same as above, we should actually show an error message to the user instead of failing silently

2022-01-21 21:52 UTC, emersonlopxs commented on src/components/HireMe/index.js
> +                <svg
We should be this to its own .svg file.

2022-01-21 21:52 UTC, emersonlopxs commented on src/components/HireMe/index.js
> +                <svg
Same as above

2022-01-21 21:52 UTC, emersonlopxs commented on src/components/HireMe/index.js
> +                <svg
Same as above

2022-01-21 21:53 UTC, emersonlopxs commented on src/components/HireMe/index.js
> +              <dl className="mt-8 space-y-6">
Nice! Didn't know about those tags!

2022-01-21 21:54 UTC, emersonlopxs commented on src/components/HireMe/index.js
> +                    <svg
We can move this to its own file as well

2022-01-21 21:54 UTC, emersonlopxs commented on src/components/HireMe/index.js
> +                    <svg
Same as above

2022-01-21 21:54 UTC, emersonlopxs commented on src/components/HireMe/index.js
> +                    <svg
Same as above

2022-01-25 18:38 UTC, Erickinhou requested changes
It's very good, but you need to hide the token, it's a sensitive data.

2022-01-25 18:38 UTC, Erickinhou commented on src/components/HireMe/index.js
> +      "user_vVXH8VL0YnDG8Gx4iRCqj"
This is a sensitive information, put this file on .env and also in netlify enviroment variable.

2022-01-25 18:38 UTC, Erickinhou commented on src/components/HireMe/index.js
> +    alert("Your email has been sent :))")
You will probably need to change the alert to react-toasty at some point. But this is a future upgrade in my vision.

2022-01-27 18:12 UTC, Erickinhou approved these changes
In my opinion, it's better use verbs on the present that describes what your commit will do.

examples:
`Add new test style.`
`Add setings section.` 
some tips:
- Never use "and" because if you are using this you probably need split your commit in two.
- Mantain the pattern using this verbs: 'add/create', 'change/update', 'remove/delete', 'improve', 'set'
- Pay attencion at spell errors.

![image](https://user-images.githubusercontent.com/57305093/151417511-4654a0d6-5506-4ce0-af16-6569d5caa69e.png)

2022-01-27 18:17 UTC, natandias approved these changes
LGTM! You can also add a description to the PR, so you'll be able to remember what this PR really does without needing to look at the files.

2022-01-27 19:48 UTC, merged